services:
  react-vite-todo:
    container_name: todotracker-frontend 
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=YOUR_KEY_HERE
